replicaCount: 3

image:
  repository: container-registry.ubs.net/ubs/ibent/uk8s-hello-whisly
  tag: "1.0.79-SNAPSHOT"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfileType: RuntimeDefault

namespace: et14157-dev-recsdiui-dev
releaseName: uk8s-hello

virtualService:
  enabled: true
  hosts:
    - "uk8s-hello-et14157-dev-recsdiui-dev.uk8s-aks-new-dev.appriv-cloud.ubs.net"
  gateway: "istio-ingress/gateway-wildcard"
