# ============================================================
# RECSDI-UI Ingress Template
# ------------------------------------------------------------
# Manages external access to RECSDI-UI via HTTP/HTTPS
# Updated for Kubernetes ≥1.19 (replaces deprecated ingress.class)
# ============================================================

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "recsdi-ui.fullname" . }}  # Helm helper for consistent naming
  labels:
    app: {{ include "recsdi-ui.name" . }}
    environment: {{ .Values.env | default "base" }}
  annotations:
    # ----------------------------------------------------------
    # ✅ TLS + Cert-Manager Configuration
    # This enables automatic HTTPS using Let's Encrypt or internal CA.
    # ----------------------------------------------------------
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- with .Values.ingress.annotations }}
    {{ toYaml . | indent 4 }}
    {{- end }}

spec:
  # ----------------------------------------------------------
  # ✅ Modern Field for Ingress Class
  # Replaces deprecated annotation "kubernetes.io/ingress.class"
  # ----------------------------------------------------------
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}

  # ----------------------------------------------------------
  # ✅ TLS Configuration
  # Pulls from values.yaml if TLS is enabled.
  # ----------------------------------------------------------
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}

  # ----------------------------------------------------------
  # ✅ Routing Rules
  # Maps domain and paths to the Service backend
  # ----------------------------------------------------------
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "recsdi-ui.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
