apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react-ui.fullname" . }}
  labels:
    app: {{ include "react-ui.name" . }}
    environment: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "react-ui.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "react-ui.name" . }}
        environment: {{ .Values.env }}
    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: react-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
{{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: {{ include "react-ui.fullname" . }}-config
