{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "react-ui.fullname" . }}
  labels:
    app: {{ include "react-ui.name" . }}
    environment: {{ .Values.env }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
{{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "react-ui.fullname" $ }}
            port:
              number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
{{- end }}
