replicaCount: 3

image:
  repository: ubsreleaseacr.azurecr.io/recsdi-ui
  tag: prod-latest
imagePullSecrets:
  - name: acr-secret

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: recsdiui.mycompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - recsdiui.mycompany.com
      secretName: recsdiui-prod-tls

config:
  VITE_ENV: "production"
  VITE_API_URL: "https://api.mycompany.com"
