replicaCount: 2

image:
  # Default: points to Dev ACR; overridden in environment files
  repository: ubsdevacr.azurecr.io/recsdi-ui
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

config: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: recsdiui-dev.mycompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - recsdiui-dev.mycompany.com
      secretName: recsdiui-dev-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
