apiVersion: v1
kind: Service
metadata:
  name: {{ include "recsdi-ui.fullname" . }}
  labels:
    app: {{ include "recsdi-ui.name" . }}
    environment: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "recsdi-ui.name" . }}
