apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uk8s-hello.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "uk8s-hello.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "uk8s-hello.fullname" . }}
    spec:
      containers:
        - name: {{ include "uk8s-hello.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              drop: {{ toJson .Values.securityContext.capabilities.drop }}
            seccompProfile:
              type: {{ .Values.securityContext.seccompProfileType }}
